name: testing

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    name: py${{ matrix.python-version }}-${{ matrix.compiler }}-${{ matrix.generator }}-${{ matrix.build_type }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']
        compiler: ['gcc', 'clang']
        generator: ['Unix Makefiles', 'Ninja']
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:

      - name: Install Criterion
        run: sudo apt-get install -y libcriterion-dev

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          which python
          python --version

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install the template with its testing dependencies
        run: python -m pip install .[testing]

      - name: Run fuzzy tests
        run: NFUZZY=100 FUZZY_COMPILERS=${{ matrix.compiler }} FUZZY_GENERATORS="${{ matrix.generator }}" CMAKE_BUILD_TYPE=${{ matrix.build_type }} python -m pytest -ra --verbose
